### ISSUE TITLE
Release versions 3.3.0 and 5.1.0

### ISSUE THREAD

**Issue by yurnov** [ansible-collections/kubernetes.core#813]
As Ansible 11 was released and included kubernetes.core collections 5.0.0 means that branch `stable-5` become the default one for the most of users who install ansible comunity package as `pip install ansible`, and documentation from the branch stable-5 (more specifically, to the released versions 5.x.y from that branch) appeared in the ansible documentation site. 

However, since Jun 10 when 5.0.0 was released, we have had a lot of smaller and bigger changes that are not included in any released version of the collection kubernetes.core, and some of them have even not been cherry-picked to the `stable-5` branch, which led, for the example that [ansible galaxy contains](https://galaxy.ansible.com/ui/repo/published/kubernetes/core/docs/) deprecated communication channels.

So, it's time to release a new release from the branch `stable-5` (that should be 5.1.0) and, probably stable-3 (that should be 3.2.0 in this case) but it's less important. 

##### SUMMARY

Release a new version 5.1.0

To do that, some PRs that weren't cherry-picked to `stable-5` should be merged in that branch (label backport-5 to be added):

- [x] #750 
- [x] #749
- [x] #756 
- [x] #765 (optional, it can be skipped as it does not affect final build, however, it is nice to have for consistency between branches)
- [x] #767
- [x] #774 
- [x] #778 
- [x] #770 
- [x] #790 
- [x] #806 

The listed above PRs are merged to `main` but don't have the label `backport-5` and are missed in branch `stable-5`.

UPDATE: to achieve working CI, the following is required:
- [x] #827 main branch
- [x] #830 main branch
- [x] #828 (backport to stable-5 for #827)
- [x] #833 (backport to stable-5 for #830)
- [x] #829 (backport to `stable-3` for #827)
- [x] #832 or #829 (backport to `stable-3` for #830)
- [x] fix CI issue (linters), issue #846, fix prepared as #848 and 
- [x] dropback #848 to `stable-5` (#849)
- [x] dropback #848 and `stable-3` (#850)
- [x] fix unstable k8_drain in integration test (#852) + backport to `stable-3` and `stable-5`

On top of that, the following PRs are to be merged into `main`:
- [x] #800 + backport to `stable-5`
- [x] #826 + backport to `stable-5` + backport to `stable-5` 
- [x] #796 
- [x] backport #796 to `stable-5` (and optionally to `stable-3`)
- [x] #831 with `[skip-changelog]` label 
- [x] #856 backport #831 to `stable-5` 
- [x] #855 backport #831 to `stable-3`
- [x] #838 with `[skip-changelog]`, no backport required (optional)

And finally:
- [x] create PR into `stable-3` with release 3.3.0, add a tag when merged;
- [x] create PR into `stable-5` with release 5.1.0, do not forget to add 3.3.0 into changelog, add tag when merged;
- [x] create PR to `main` with port 5.1.0 update and change version in `galaxy.yaml` to `5.2.0-dev0` to easy see that it's not released version in the output of `ansible-galaxy collection list` when collection is installed from git.
- [x] notify @newsbot:ansible.im to include released versions 3.3.0 and 5.1.0 in the next Ansible Bullhorn.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

kubernetes.core

##### ADDITIONAL INFORMATION

I can create the above-mentioned PRs (in the "and finally" part) in the similar way as #746, but need support from maintainers with code review, merge and tags.

**Comment by yurnov** [comment]
Backport of #767 to `stable-3` created as #822 due to merge conflict resolved manually

**Comment by yurnov** [comment]
backport of #774 to `stable-5` created as #823 due to [patchback](https://github.com/apps/patchback) bot [fail](https://github.com/ansible-collections/kubernetes.core/pull/774#issuecomment-2536394495)

**Comment by yurnov** [comment]
I have updated issue to reflect the actual status and additional effort

**Comment by yurnov** [comment]
Updated with CI issue (linters), please find #848. 

@abikouo, would you like to review that PR?

**Comment by yurnov** [comment]
PR #802 requires actions from @b0z02003, and he didn't respond to a request from @abikouo. I think that this can be skipped in release 5.1.0 (alternatively, I can help with the rebase and testing part, if the PR author will allow me to commit to b0z02003/kubernetes.core)

**Comment by gravesm** [comment]
I think we should skip it and do the release the beginning of next week.

**Comment by yurnov** [comment]
> I think we should skip it and do the release the beginning of next week.

Sure. Thanks, @gravesm for your (and @abikouo) valuable support with this issue, I didn't expect this amount of CI-related work.

Would it be ok if I create PRs for the remaining part?

**Comment by gravesm** [comment]
Yeah, that would be great. Thanks for your help in pushing this forward.

**Comment by yurnov** [comment]
> Yeah, that would be great. Thanks for your help in pushing this forward.

Thanks, I will do in Monday. 

BTW, would you please add `skip-changelog` to #860 and #859 to merge them?

**Comment by gravesm** [comment]
> BTW, would you please add skip-changelog to https://github.com/ansible-collections/kubernetes.core/pull/860 and https://github.com/ansible-collections/kubernetes.core/pull/859 to merge them?

They're both merged.

**Comment by yurnov** [comment]
> > BTW, would you please add skip-changelog to [#860](https://github.com/ansible-collections/kubernetes.core/pull/860) and [#859](https://github.com/ansible-collections/kubernetes.core/pull/859) to merge them?
> 
> They're both merged.

sorry, my fault, I meant #855 and #856 that is backports of #831, they are still opened with failed CI on changelog

**Comment by b0z02003** [comment]
> PR [#802](https://github.com/ansible-collections/kubernetes.core/pull/802) requires actions from [@b0z02003](https://github.com/b0z02003), and he didn't respond to a request from [@abikouo](https://github.com/abikouo). I think that this can be skipped in release 5.1.0 (alternatively, I can help with the rebase and testing part, if the PR author will allow me to commit to b0z02003/kubernetes.core)

I'm so sorry for the late reply. I do understand if the PR skips the next release, in the mean time, I've just rebased it and added @yurnov as a contributor. I'll try to look for the failing integration test on my part today and, hopefully, I'll be able to provide you with a clean PR for this next release (still, I'll understand if you skip it).

**Comment by yurnov** [comment]
> > PR [#802](https://github.com/ansible-collections/kubernetes.core/pull/802) requires actions from [@b0z02003](https://github.com/b0z02003), and he didn't respond to a request from [@abikouo](https://github.com/abikouo). I think that this can be skipped in release 5.1.0 (alternatively, I can help with the rebase and testing part, if the PR author will allow me to commit to b0z02003/kubernetes.core)
> 
> I'm so sorry for the late reply. I do understand if the PR skips the next release, in the mean time, I've just rebased it and added [@yurnov](https://github.com/yurnov) as a contributor. I'll try to look for the failing integration test on my part today and, hopefully, I'll be able to provide you with a clean PR for this next release (still, I'll understand if you skip it).

Let see how it will work in monday

**Comment by yurnov** [comment]
Hi @gravesm @abikouo,

during the weekend the CI part for #802 was completed, should we include this PR in the release? Could you please take a look?

Both options, to include this PR, or to release without and keep 802 and #786 for the next release will be fine for me.

**Comment by gravesm** [comment]
Let's continue with the release as planned and leave these for the next release. We can probably try and plan on a 5.2.0 release in a month.

**Comment by yurnov** [comment]
PR for 3.3.0 https://github.com/ansible-collections/kubernetes.core/pull/863
PR for 5.1.0 https://github.com/ansible-collections/kubernetes.core/pull/865

**Comment by yurnov** [comment]
Releases [3.3.0](https://github.com/ansible-collections/kubernetes.core/releases/tag/3.3.0) and [5.1.0](https://github.com/ansible-collections/kubernetes.core/releases/tag/5.1.0) are live! 

The remaining part is a post-5.1.0 update #866

**Comment by yurnov** [comment]
Done
